spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AlgerFan/config-repo.git
          username: AlgerFan
          password:
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"