eureka:
  client:
    service-url:
      defaultZone: http://192.168.43.137:8080/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: lovewlgzs
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud_sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
